### PR TITLE
Add Laravel 8.x and Corcel 5.x compatibility

### PR DESCRIPTION
**Pull request by twmbx**
allow jgrossi/corcel 5.0
added laravel/legacy-factories

### CODE REVIEW

**Comment by Dartui** [comment]
Hello, thanks for this MR. Could you please bump minimum PHP version to 7.3 in composer.json? Also in github workflow (https://github.com/corcel/woocommerce/blob/master/.github/workflows/main.yml) change PHP versions from `7.2, 7.3, 7.4` to `7.3, 7.4, 8.0`, because tests are failing.

**Comment by twmbx** [comment]
@Dartui looks like php 8.0 breaks the tests because the laravel dependencies don't support it as they specify a requirement for version ^7.3. I'm going to remove the php bits to get the tests to pass.

**Comment by Dartui** [comment]
Sure, feel free to make as many changes as needed to make this work

**Comment by twmbx** [comment]
@Dartui looks like this is good to go now. :tada:

**Comment by Dartui** [comment]
Since [this](https://github.com/laravel/framework/pull/33388) is not merged we cannot add PHP 8.0 to tests. 

For now this MR looks good to me.

**Pull request merged**
